spring.application.name=resume-screening
spring.datasource.url=jdbc:postgresql://localhost:5432/aeroto_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true